version: '3'

services:

  backendserver:
    image: 'santiagot1105/backend-praxis-gildedrose:latest'
    ports:
           - "8081:8080"
    environment:
           - DB_HOST_IP=group4-rds.cqqmj66dxtlw.us-east-1.rds.amazonaws.com
           - DB_USERNAME=group4
           - DB_PASSWORD=Perficient2022*
  frontend:
    image: 'santiagot1105/frontend-praxis-gildedrose:latest'
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    environment:
           - API_URL_IP=backendserver
    ports:
           - "4200:4200"